[2025-08-17T04:00:00.434+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: churn_pipeline_dag.raw_data_storage manual__2025-08-17T03:59:55.708749+00:00 [queued]>
[2025-08-17T04:00:00.445+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: churn_pipeline_dag.raw_data_storage manual__2025-08-17T03:59:55.708749+00:00 [queued]>
[2025-08-17T04:00:00.445+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-08-17T04:00:00.459+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): raw_data_storage> on 2025-08-17 03:59:55.708749+00:00
[2025-08-17T04:00:00.469+0000] {standard_task_runner.py:57} INFO - Started process 80 to run task
[2025-08-17T04:00:00.474+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'churn_pipeline_dag', 'raw_data_storage', 'manual__2025-08-17T03:59:55.708749+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/churn_pipeline_dag.py', '--cfg-path', '/tmp/tmp4wfhul5x']
[2025-08-17T04:00:00.476+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask raw_data_storage
[2025-08-17T04:00:00.544+0000] {task_command.py:415} INFO - Running <TaskInstance: churn_pipeline_dag.raw_data_storage manual__2025-08-17T03:59:55.708749+00:00 [running]> on host b283dd67aa38
[2025-08-17T04:00:00.682+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='churn_pipeline_dag' AIRFLOW_CTX_TASK_ID='raw_data_storage' AIRFLOW_CTX_EXECUTION_DATE='2025-08-17T03:59:55.708749+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-17T03:59:55.708749+00:00'
[2025-08-17T04:00:00.809+0000] {logging_mixin.py:151} INFO - ‚ùå Script failed: /opt/***/02_Source_Code/step3_raw_data_storage/raw_storage.py
[2025-08-17T04:00:00.810+0000] {logging_mixin.py:151} INFO - STDOUT: 
[2025-08-17T04:00:00.810+0000] {logging_mixin.py:151} INFO - STDERR: python: can't open file '/opt/***/02_Source_Code/step3_raw_data_storage/raw_storage.py': [Errno 2] No such file or directory
[2025-08-17T04:00:00.811+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/churn_pipeline_dag.py", line 12, in run_script
    result = subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '/opt/airflow/02_Source_Code/step3_raw_data_storage/raw_storage.py']' returned non-zero exit status 2.
[2025-08-17T04:00:00.827+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=churn_pipeline_dag, task_id=raw_data_storage, execution_date=20250817T035955, start_date=20250817T040000, end_date=20250817T040000
[2025-08-17T04:00:00.844+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task raw_data_storage (Command '['python', '/opt/airflow/02_Source_Code/step3_raw_data_storage/raw_storage.py']' returned non-zero exit status 2.; 80)
[2025-08-17T04:00:00.888+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-17T04:00:00.912+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
