[2025-08-17T01:03:50.809+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-17T01:03:50.835+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: churn_pipeline_dag.raw_data_storage manual__2025-08-17T01:03:44.547804+00:00 [queued]>
[2025-08-17T01:03:50.842+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: churn_pipeline_dag.raw_data_storage manual__2025-08-17T01:03:44.547804+00:00 [queued]>
[2025-08-17T01:03:50.844+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-17T01:03:50.858+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): raw_data_storage> on 2025-08-17 01:03:44.547804+00:00
[2025-08-17T01:03:50.868+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=104) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-17T01:03:50.870+0000] {standard_task_runner.py:64} INFO - Started process 106 to run task
[2025-08-17T01:03:50.869+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'churn_pipeline_dag', 'raw_data_storage', 'manual__2025-08-17T01:03:44.547804+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/churn_pipeline_dag.py', '--cfg-path', '/tmp/tmpn2gi7g01']
[2025-08-17T01:03:50.872+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask raw_data_storage
[2025-08-17T01:03:50.922+0000] {task_command.py:426} INFO - Running <TaskInstance: churn_pipeline_dag.raw_data_storage manual__2025-08-17T01:03:44.547804+00:00 [running]> on host 6a8931c175ca
[2025-08-17T01:03:51.023+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='churn_pipeline_dag' AIRFLOW_CTX_TASK_ID='raw_data_storage' AIRFLOW_CTX_EXECUTION_DATE='2025-08-17T01:03:44.547804+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-17T01:03:44.547804+00:00'
[2025-08-17T01:03:51.025+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-17T01:03:51.109+0000] {logging_mixin.py:188} INFO - ERRORS: python: can't open file '/opt/***/dags/../02_Source_Code/step3_raw_data_storage/raw_storage.py': [Errno 2] No such file or directory
[2025-08-17T01:03:51.110+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-17T01:03:51.112+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-17T01:03:51.126+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=churn_pipeline_dag, task_id=raw_data_storage, run_id=manual__2025-08-17T01:03:44.547804+00:00, execution_date=20250817T010344, start_date=20250817T010350, end_date=20250817T010351
[2025-08-17T01:03:51.165+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-08-17T01:03:51.196+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-17T01:03:51.198+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
