[2025-08-17T01:03:48.568+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-17T01:03:48.596+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: churn_pipeline_dag.data_ingestion manual__2025-08-17T01:03:44.547804+00:00 [queued]>
[2025-08-17T01:03:48.604+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: churn_pipeline_dag.data_ingestion manual__2025-08-17T01:03:44.547804+00:00 [queued]>
[2025-08-17T01:03:48.605+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-17T01:03:48.622+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_ingestion> on 2025-08-17 01:03:44.547804+00:00
[2025-08-17T01:03:48.633+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=92) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-17T01:03:48.636+0000] {standard_task_runner.py:64} INFO - Started process 102 to run task
[2025-08-17T01:03:48.635+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'churn_pipeline_dag', 'data_ingestion', 'manual__2025-08-17T01:03:44.547804+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/churn_pipeline_dag.py', '--cfg-path', '/tmp/tmpo1lhl210']
[2025-08-17T01:03:48.638+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask data_ingestion
[2025-08-17T01:03:48.710+0000] {task_command.py:426} INFO - Running <TaskInstance: churn_pipeline_dag.data_ingestion manual__2025-08-17T01:03:44.547804+00:00 [running]> on host 6a8931c175ca
[2025-08-17T01:03:48.818+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='churn_pipeline_dag' AIRFLOW_CTX_TASK_ID='data_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-08-17T01:03:44.547804+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-17T01:03:44.547804+00:00'
[2025-08-17T01:03:48.821+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-17T01:03:48.897+0000] {logging_mixin.py:188} INFO - ERRORS: python: can't open file '/opt/***/dags/../02_Source_Code/step2_data_ingestion/data_ingestion.py': [Errno 2] No such file or directory
[2025-08-17T01:03:48.898+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-17T01:03:48.899+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-17T01:03:48.911+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=churn_pipeline_dag, task_id=data_ingestion, run_id=manual__2025-08-17T01:03:44.547804+00:00, execution_date=20250817T010344, start_date=20250817T010348, end_date=20250817T010348
[2025-08-17T01:03:48.972+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-08-17T01:03:49.003+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-17T01:03:49.006+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
